Quiron.LojaVirtual.Web/Models/ProdutosViewModel.cs
using Quiron.LojaVirtual.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Quiron.LojaVirtual.Web.Models
{
    public class ProdutosViewModel
    {
        public IEnumerable<Produto> Produtos { get; set; }
        public Paginacao Paginacao { get; set; }

        public string CategoriaAtual { get; set; }
    }
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Controllers/ProdutoController.cs
using Quiron.LojaVirtual.Dominio.Entidades;
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Areas.Administrativo.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        private ProdutosRepositorio _repositorio;

        // GET: Administrativo/Produto
        public ActionResult Index()
        {
            _repositorio = new ProdutosRepositorio();
            var produtos = _repositorio.Produtos;
            return View(produtos);
        }

        public ViewResult Alterar (int produtoId)
        {
            _repositorio = new ProdutosRepositorio();
            Produto produto = _repositorio.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);
            return View(produto);
        }

        [HttpPost]
        public ActionResult Alterar(Produto produto)
        {
            if(ModelState.IsValid)
            {
                _repositorio = new ProdutosRepositorio();
                _repositorio.Salvar(produto);
                
                TempData["Mensagem"] = string.Format("{0} foi salvo com sucesso!", produto.Nome);
                return RedirectToAction("index");
            }

            return View(produto);
        }

        public ViewResult NovoProduto()
        {
            return View("Alterar", new Produto());
        }

        //[HttpPost]
        //public ActionResult Excluir(int produtoId)
        //{
        //    _repositorio = new ProdutosRepositorio();
        //    Produto prod = _repositorio.Excluir(produtoId);

        //    if (prod != null)
        //    {
        //        TempData["mensagem"] = string.Format("{0} excluido com sucesso!", prod.Nome);
        //    }
        //    return RedirectToAction("Index");
        //}


        [HttpPost]
        public JsonResult Excluir(int produtoId)
        {
            string mensagem = string.Empty;
            _repositorio = new ProdutosRepositorio();
            Produto prod = _repositorio.Excluir(produtoId);

            if (prod != null)
            {
                mensagem = string.Format("{0} excluido com sucesso!", prod.Nome);
            }
            return Json(mensagem, JsonRequestBehavior.AllowGet);
        }

    }
}

Quiron.LojaVirtual.Web/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quiron.LojaVirtual.Dominio.Repositorio;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutosRepositorio _repositorio;
        // GET: Produto
        public ActionResult Index()
        {
            _repositorio = new ProdutosRepositorio();
            var produtos = _repositorio.Produtos.Take(10);

            return View(produtos);
        }
    }
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Alterar.cshtml
@model Quiron.LojaVirtual.Dominio.Entidades.Produto

@{
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

@*@using (Html.BeginForm())
    {
        //Renderiza rapidamente um formulario, de acordo com a entidade produtos do dominio
        @Html.EditorForModel()
        <input type="submit" value="Salvar" />
        @Html.ActionLink("Cancelar e Retornar", "Index")
    }*@


<div class="panel">
    <div class="panel-heading">
        <h3>Alterar - @Model.Nome</h3>
    </div>

    @using (Html.BeginForm("Alterar", "Produto"))
    {
        <div class="panel-body">

            @Html.HiddenFor(p => p.ProdutoId)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "ProdutoId")
                {
                    <div class="form-group">
                        <label>
                            @(property.DisplayName ?? property.PropertyName)
                        </label>

                        @if (property.PropertyName == "Descricao")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }

                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }

        </div>

        <div class="panel-footer">
            <input type="submit" value="Salvar" class="btn btn-primary" />
            @Html.ActionLink("Cancelar e Retornar", "Index", null, new {@class="btn btn-default" })
        </div>
    }

</div>

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Confirmacao.cshtml
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="deleteModalLabel">Exclusão</h4>
            </div>

            <div class="modal-body">
                <input type="hidden" />
                <p>Deseja excluir o produto <em><strong>"<span></span>"</strong></em>&nbsp;?</p>
            </div>

            <div class="modal-footer">
                <button class="btn btn-success" type="button">Confirmar</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>

    $(function () {

        //Abrir o modal

        $(".btn-xs").click(function (e) {
            e.preventDefault();
            var id = this.id;
            var nome = this.name;
            $("#deleteModal .modal-body input[type=hidden]").val(id);
            $("#deleteModal .modal-body span").text(nome);
            $("#deleteModal").modal('show');
        });

        $("#deleteModal .modal-footer button").click(function (e) {
            e.preventDefault();
            var url = "/Administrativo/Produto/Excluir/";
            var id = $(".modal-body input[type=hidden]").val();
            var rowNo = '#row-' + id;

            $.ajax({
                url: url,
                type: 'post',
                dataType: 'json',
                data: { produtoId: id },
                beforeSend: function () {
                    var loading = "<span><em>Excluindo</em>&nbsp;<i class='glyphicon glyphicon-refresh icon-refresh-animate'></i></span>";
                    $('#deleteModal .modal-header h4').after(loading);
                },
                success: function () {

                    $('#deleteModal').modal('hide');

                    $(rowNo).animate({ opacity: 0.0 }, 400, function () {
                        $(rowNo).remove();
                    });
                },
                complete: function (data) {
                    $("#divexcluir").empty();
                    $("#divexcluir").addClass("alert alert-success");
                    $("#divexcluir").html(data.responseText);
                }
            });
        });
    });
</script>